# Generated by Django 4.2.7 on 2023-11-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_teacher_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='teacher',
            name='level',
            field=models.IntegerField(default=1, verbose_name='worker_level'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
