# Generated by Django 4.2.7 on 2023-12-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
