# Generated by Django 5.0 on 2023-12-28 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_continousassessment_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='category',
            field=models.CharField(choices=[('Pre_JSS', 'Pre_JSS'), ('Nursery', 'Nursery'), ('Primary', 'Primary'), ('Junior Secondary', 'Junior Secondary'), ('Senior Secondary', 'Senior Secondary')], default='Nursery', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='main.grade'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teacher'),
        ),
    ]
