# Generated by Django 5.0 on 2023-12-29 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_class_student_my_class_section_class_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.class'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_class',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='main.grade'),
        ),
    ]
